package code.engine;

public enum EntityType {
	//TODO cleanup
	PLAYER, ENEMY, UI_ELEMENT, PLAYER_PROJECTILE, PROJECTILE, MOUSE1ITEM, MOUSE3ITEM, SHIPITEM,DROPPEDITEM, SOUND, HITPARTICLE, SPAWNER, LABEL, TRAILSEGMENT, ITEM, EFFECT, VISUAL_EFFECT
}
