package code.engine;

public enum EntityType {
	PLAYER, ENEMY, UI_ELEMENT, PLAYER_PROJECTILE, ENEMY_PROJECTILE, MOUSE1ITEM, MOUSE3ITEM, OTHERITEM, SOUND, PARTICLE, SPAWNER, LABEL, TRAILSEGMENT
}
